---
- name: Dump event messages
  hosts: localhost
  sources:
    - benthomasson.eda.kafka:
        host: broker
        port: 9092
        topic: bobbycar-speed-alert
        group_id:

  rules:
    - name: debug
      condition: event.speedAvg is defined
      action:
        debug:
