---
- name: Listen for incoming track failures on a webhook
  hosts: all
  sources:
    - benthomasson.eda.webhook:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Sandbox failure
      condition: event.payload.type == "sandbox.failed"
      action:
        run_playbook:
          name: track-alert.yml
