- name: ASB events
  hosts: localhost
  sources:
    - ansible.eda.azure_service_bus:
        conn_str: "{{ conn_str }}"
        queue_name: "{{ queue_name }}"
  rules:
    - name: Debug event
      condition: event.meta is defined
      action:
        debug:
