- name: ASB events
  hosts: localhost
  sources:
    - ansible.eda.azure_service_bus:
        conn_str: "{{ conn_str }}"
        queue_name: "{{ queue_name }}"
  rules:
    - name: Debug event
      condition: event.payload.type == "sandbox.failed"
      action:
        run_job_template:
          name: Create Github issue
          organization: TMM
