---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - dynatrace.event_driven_ansible.dt_esa_api:
        dt_api_host: "https://qxb15856.apps.dynatrace.com"
        dt_api_token: "dt0c01.NULN533JYQTOUZAYONS5QYUL.4ZSF3OMV7BS6PEMGBBDWXDPJVHWX6WLC6YPVQPMAZH7KLH6RZBHAKL6UHJNRDXTQ"
        delay: 60 (Default is 1 min) i.e plugin runs every 1 minute

  rules:
    - name: Log4Shell Vulnerability
      condition: event.problemTitle contains "JNDI Injection"
      action:
        run_job_template:
          name: "Notify DevSecOps Team"
          organization: "Default"
    - name: Problem payload Dynatrace for App Failure rate increase issue
      condition: event.problemTitle contains "Failure rate increase"
      action:
        run_job_template:
          name: "Remediate Application issue"
          organization: "Default"
    - name: Update comments in Dynatrace
      condition: 
        all: 
          - event.status == "OPEN"
      action:
        run_playbook:
          name: dt-update-comments.yml
