- name: Instruqt events on SQS
  hosts: localhost
  sources:
    - ansible.eda.aws_sqs_queue:
        access_key: "{{ aws_access_key }}"
        secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        name: "{{ queue_name }}"
        delay_seconds: "{{ delay_seconds }}"


  rules:
    # Instruqt doesn't include track_slug for sandbox.failed only track_id
    # track_id mxin1twsyurv is aap-on-ocp
    - name: R1 - Instruqt - SANDBOX FAILURE
      condition: event.body.headers.application == "instruqt" and event.body.body.type == "sandbox.failed"
      action:
        run_job_template:
          name: InstruqtTrackFailure
          organization: Default
          job_args:
            extra_vars:
              short_description: "Track failure: {{ event.body.body.track_slug }}"
              description: |
                Timestamp: {{ event.body.body.track_slug }}
                Participant ID: {{ event.body.body.participant_id }}

    - name: R2 - Instruqt - ServiceNow sandbox CREATED
      condition: event.body.headers.application == "instruqt" and event.body.body.type == "sandbox.created" and event.body.body.track_slug == "getting-started-servicenow-automation"
      action:
        debug:

    - name: R3 - Instruqt - ServiceNow sandbox STOPPED
      condition: event.body.headers.application == "instruqt" and event.body.body.type == "sandbox.cleaned" and event.body.body.track_slug == "getting-started-servicenow-automation"
      action:
        debug:

    # Instruqt doesn't include track_slug for review.* only track_id
    - name: R4 - Instruqt - New review with feedback
      condition: event.body.headers.application == "instruqt" and event.body.body.type == "review.updated"
      action:
        debug:

    # - name: R5 - Instruqt - catch all instruqt events
    #   condition: event.body.headers.application == "instruqt"
    #   action:
    #     debug:

    # - name: R6 - Instruqt - catch all events
    #   condition: event.body is defined
    #   action:
    #     debug:
