- name: Instruqt events on SQS
  hosts: localhost
  sources:
    - ansible.eda.aws_sqs_queue:
        access_key: "{{ aws_access_key }}"
        secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        name: "{{ queue_name }}"
        delay_seconds: "{{ delay_seconds }}"


  rules:
    - name: R1 - Debug1
      condition: event.Body.headers.application == "instruqt"
      action:
        debug:

    - name: R2 - Debug2
      condition: event.Body.headers is defined
      action:
        debug:
