- name: Instruqt events on SQS
  hosts: localhost
  sources:
    - ansible.eda.aws_sqs_queue:
        access_key: "{{ aws_access_key }}"
        secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        name: "{{ queue_name }}"
        delay_seconds: "{{ delay_seconds }}"


  rules:
    - name: R1 - Instruqt - sandbox failure!
      condition: event.body.headers.application == "instruqt" and event.body.body.type == "sandbox.failed"
      action:
        debug:

    - name: R2 - Instruqt - ServiceNow sandbox created
      condition: event.body.headers.application == "instruqt" and event.body.body.type == "sandbox.created" and event.body.body.track_slug == "getting-started-servicenow-automation"
      action:
        debug:

    - name: R3 - Instruqt - event catchall
      condition: event.body.headers is defined
      action:
        debug:
