---
- name: Listen webhook POSTs from gitea
  hosts: appnodes
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Dump event
      condition: event.payload.repository.name=="test-app"
      action:
        run_playbook:
          name: playbooks/dump.yml
