---
- name: Listen for birthday wishes an endpoint
  hosts: all
  sources:
    - benthomasson.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Andrius's birthday
      condition: event.payload.message == "Happy Birthday, Andrius!"
      action:
        run_playbook:
          name: playbooks/thanks.yml
