---
- name: pull_request -- update application repo
  hosts: localhost
  gather_facts: false
  tasks:

  - name: pull_request -- Check if repo exists locally
    ansible.builtin.stat:
      path: "/tmp/{{ event.repo_name }}"
    register: repo_stat

  - name: pull_request -- Clone application repository 
    ansible.builtin.git:
      repo: "{{ event.clone_url }}"
      dest: "/tmp/{{ event.repo_name }}"
      clone: true
      update: true
    when: repo_stat.stat.exists == false
    register: repo_cloned

  - name: pull_request -- Update application repository to event ref 
    ansible.builtin.git:
      repo: "{{ event.clone_url }}"
      dest: "/tmp/{{ event.repo_name }}"
      clone: true
      update: true
      version: "{{ event.gitref }}"
    register: repo_cloned

  - set_fact:
      cacheable: true
      repo_stat: "{{ repo_stat }}"
      cloned: "{{ repo_cloned }}"
      etype: "{{ event.type }}"
      erepo: "{{ event.repo_name }}"
      eref: "{{ event.gitref }}"
      eauthor: "{{ event.author }}"
