---
- name: update application repo
  hosts: localhost
  gather_facts: false
  tasks:

  - name: Clone/update application repository to event ref
    ansible.builtin.git:
      repo: "{{ event.repo.clone_url }}"
      dest: "/tmp/{{ event.repo.name }}"
      clone: true
      update: true
      reference: "{{ event.gitref }}"
    register: repo_cloned

  - debug:
      var: repo_cloned

  - set_fact:
      cacheable: true
      cloned: "{{ repo_cloned }}"
      gitref: "{{ event.gitref }}"
      commit: "{{ event.commit }}"