---
- name: New positive review on Instruqt track
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    slack_token:
    slack_username:
    slack_channel:
    api_url: "https://play.instruqt.com/graphql"
    api_key: 
    track_id: "{{ ansible_eda.event.body.body.track_id }}"
    content: "{{ ansible_eda.event.body.body.content }}"
    query: >
      {
        "query": "query { track(trackID: \"{{ track_id }}\") { slug, developers { profile { display_name } } } }"
      }
  tasks:
    - name: Query track details
      ansible.builtin.uri:
        url: "{{ api_url }}"
        method: POST
        headers:
          Authorization: "Bearer {{ api_key }}"
          Content-Type: "application/json"
        body: "{{ query }}"
        body_format: json
        return_content: true
      register: response

    - name: Extract developer names
      set_fact:
        developer_names: "{{ response.json.data.track.developers | map(attribute='profile.display_name') | list }}"
        
    - name: Print review
      ansible.builtin.debug:
        msg: |
          New positive review
          Track: "{{ response.json.data.track.slug }}"
          Content: "{{ content }}"
          Developers: "{{ developer_names | join(', ') }}"

    - name: Send notification message via Slack
      community.general.slack:
        token: "{{ slack_token }}"
        msg: "*Instruqt positive review*\n------------------------\n*Track:* {{ response.json.data.track.slug }}\n*Developers:* {{ developer_names | join(', ')\n*Review:* {{ content }} }}"
        username: "{{ slack_username }}"
        channel: "{{ slack_channel }}"
