---
- name: Instruqt alert
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: "{{ ansible_date_time.iso8601 }} - {{ event.payload.type }}: {{ event.payload.track_slug}} {{ event.payload.participant_id }}"